package com.kafonin.employee.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "EMPLOYEE")
public class People implements Serializable {
    
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private String      peopleId;
    private String      firstName;
    private String      lastName;
    private String      company;
    private String      job;

    public People() {}

    public People(String peopleId, String firstName, String lastName, String company, String job) {
        this.peopleId           = peopleId;
        this.firstName          = firstName;
        this.lastName           = lastName;
        this.company            = company;
        this.job                = job;
    }

    // Getters and setters

    @DynamoDBHashKey(attributeName = "peopleId")
    @DynamoDBAutoGeneratedKey
    public String getPeopleId() {
        return peopleId;
    }

    public void setPeopleId(String peopleId) {
        this.peopleId = peopleId;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBRangeKey
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute
    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @DynamoDBAttribute
    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }
}